### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by Berstanio** [tommyettinger/gdx-liftoff-ui-redesign#7]
I didn't looked through the code, just played with the UI.
First of all, I think it looks pretty good!
Just a few notes:
- The UI shows a "ROBOVM VERSION" field. It also shows when not even selecting the iOS backend, but furthermore I think it is not really relevant at all to configure. 
- The screen also provides "gradle tasks" to execute after generation. What is the use case for this?
- The Third-Party thing says, I have two extensions selected, while I don’t have any selected
- Fullscreen doesn’t allow for “quick project” generation, is this intended? 
- Some templates are marked with a "*", and you can only see why with a tooltip. I think some legend at the bottom would be better, since the tooltip is very easy to miss

These are just a few things I noticed, very great work tho!

**Comment by raeleus** [comment]
I agree about the robovm bit, but if I recall every project has the version listed in the build.gradle.TEt might want to comment on its necessity.
I haven't needed it, but you can make it run the LWJGL build right away to make sure your build environment works. Stuff like that.
I was hoping that the third party was one off thing, but it seems to be affecting other users. Thanks.
Yeah, fullscreen is supposed to be its own sort of thing. I wonder how important it is to have quick project to begin with. Do you intend on using quick project?
I'll find a solution for those * items. Thanks!

**Comment by Berstanio** [comment]
>  I haven't needed it, but you can make it run the LWJGL build right away to make sure your build environment works. Stuff like that.

Yeah, but I just thought that it takes a very prominent place, for something that might never be used. But I don't really know all the ways liftoff is used, I might be wrong on this.

> I wonder how important it is to have quick project to begin with. Do you intend on using quick project?

I do not, but I can also count the times I generated a project with two bits, so I'm not the right person to comment on the necessity of it. I just thought I mention it, in case it was unintended.

**Comment by tommyettinger** [comment]
OK, Quick Project is gone now, it was sadly not as helpful as we thought. RoboVM is currently linked to the Liftoff release, which isn't optimal but Liftoff has an update reminder now, so it shouldn't be too bad. I've never used the Gradle tasks, some people do seem to use them though. Third-party thing is fixed, some preferences data was persisting.

That leaves only the asterisks...
